const ACTIONS = {
	LOGIN: "LOGIN",
	SET_TOKEN: "SET_TOKEN",
	GET_USER: "GET_USER",
	GET_ALL_USERS: "GET_ALL_USERS",
	LOGOUT: "LOGOUT",
	GET_ALL_RESUMES: "GET_ALL_RESUMES",
};

export default ACTIONS;
